spring.application.name=Fin
gemini.api.key=AIzaSyAxFVr24bfPhT0L7WcoDBvj2zlInOXLdBs
google.application.credentials.path=C:/Users/dhrub/OneDrive/Desktop/Dhrubo Mac/FinoStepWebsite/finostep-15d207ad9fbb.json